version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://todo:todo@db:5432/todo
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      # - ../alembic.ini:/app/alembic.ini

volumes:
  postgres_data:
